version: "3.9"

services:
  api1: &api
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api1
    environment:
      - DEFAULT_CONNECTION=Host=db;Username=local_user;Password=local_password;Database=local_db;Pooling=true;MinPoolSize=10;Maximum Pool Size=200;Timeout=120;Command Timeout=60;
    depends_on:
      - db
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "80MB"

  api2:
    <<: *api
    environment:
      - DEFAULT_CONNECTION=Host=db;Username=local_user;Password=local_password;Database=local_db;Pooling=true;Pooling=true;MinPoolSize=10;Maximum Pool Size=200;Timeout=120;Command Timeout=60;
    container_name: api2

  db:
    image: "postgres:16.0-alpine3.18"
    env_file:
      - .env
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    deploy:
      resources:
        limits:
          cpus: "0.8"
          memory: "350MB"

  # haproxy:
  #   image: haproxy:2.9-alpine
  #   volumes:
  #     - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
  #   depends_on:
  #     - api1
  #     - api2
  #   ports:
  #     - 9999:9999
  #   restart: unless-stopped
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: "0.2"
  #         memory: "30MB"

  nginx:
    image: nginx:1.21-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - 9999:9999
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "30MB"

networks:
  default:
    driver: bridge
    name: rinha-2024
