services:
  database:
    image: "postgres:16.0-alpine3.18"
    env_file:
      - ../.env
    volumes:
      - ../init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    command: postgres -c max_connections=500 -c shared_buffers=50MB -c synchronous_commit=off -c fsync=off -c full_page_writes=off
