services:
  database:
    image: postgres:16.2
    env_file:
      - ../.env
    volumes:
      - ../init:/docker-entrypoint-initdb.d
      # - ../postgresql.conf:/etc/postgresql/postgresql.conf
    # command: postgres -c config_file=/etc/postgresql/postgresql.conf
    command: "postgres -c max_connections=1000 -c shared_buffers=128MB -c synchronous_commit=off -c fsync=off -c full_page_writes=off"
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: "0.8"
          memory: "400MB"
