services:
  database:
    image: "postgres:16.0-alpine3.18"
    env_file:
      - ../.env
    volumes:
      - ../init:/docker-entrypoint-initdb.d
      - ../postgresql.conf:/etc/postgresql/postgresql.conf
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: "0.8"
          memory: "400MB"
